// <auto-generated />
using System;
using OpenCredentials;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OpenCredentials.Migrations
{
    [DbContext(typeof(OpenCredentialsContext))]
    [Migration("20260426001417_AddScannerControl")]
    partial class AddScannerControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenCredentials.ExposureTypeEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("AutoInform")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Name");

                    b.ToTable("ExposureTypes", (string)null);
                });

            modelBuilder.Entity("OpenCredentials.FindingEntity", b =>
                {
                    b.Property<string>("KeySha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RepoFullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("AuthorLogin")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExposureType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("ApiKey");

                    b.Property<string>("FileHtmlUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("KeyLength")
                        .HasColumnType("int");

                    b.Property<string>("KeyPrefix")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelHint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RepoHtmlUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("KeySha256", "RepoFullName", "FilePath");

                    b.HasIndex("AuthorLogin")
                        .HasDatabaseName("IX_Findings_Author");

                    b.HasIndex("ExposureType")
                        .HasDatabaseName("IX_Findings_ExposureType");

                    b.HasIndex("Provider")
                        .HasDatabaseName("IX_Findings_Provider");

                    b.HasIndex("RepoFullName")
                        .HasDatabaseName("IX_Findings_Repo");

                    b.ToTable("Findings", (string)null);
                });

            modelBuilder.Entity("OpenCredentials.NoticeEntity", b =>
                {
                    b.Property<string>("KeySha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RepoFullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Channel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueHtmlUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("KeySha256", "RepoFullName", "FilePath", "Channel");

                    b.HasIndex("RepoFullName")
                        .HasDatabaseName("IX_Notices_Repo");

                    b.ToTable("Notices", (string)null);
                });

            modelBuilder.Entity("OpenCredentials.RemediationCheckEntity", b =>
                {
                    b.Property<string>("KeySha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RepoFullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("KeySha256", "RepoFullName", "FilePath", "CheckedAtUtc");

                    b.HasIndex("KeySha256", "RepoFullName", "FilePath")
                        .HasDatabaseName("IX_RemediationChecks_Finding");

                    b.ToTable("RemediationChecks", (string)null);
                });

            modelBuilder.Entity("OpenCredentials.ScannedFileEntity", b =>
                {
                    b.Property<string>("RepoFullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("RepoFullName", "FilePath");

                    b.ToTable("ScannedFiles", (string)null);
                });

            modelBuilder.Entity("OpenCredentials.ScannerControlEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("ScannerControl", (string)null);
                });

            modelBuilder.Entity("OpenCredentials.FindingEntity", b =>
                {
                    b.HasOne("OpenCredentials.ExposureTypeEntity", "ExposureTypeNav")
                        .WithMany()
                        .HasForeignKey("ExposureType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExposureTypeNav");
                });
#pragma warning restore 612, 618
        }
    }
}
